"""Frozen schema captured at 58a3fea; never import live ORM."""
from alembic import op
import sqlalchemy as sa

revision = '0001_baseline'
down_revision = None
branch_labels = None
depends_on = None

def upgrade():
# ### commands auto generated by Alembic - please adjust! ###
    op.create_table('gas_sources',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=16), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('supplier', sa.String(length=64), nullable=False),
    sa.Column('gas_type', sa.String(length=16), nullable=False),
    sa.Column('contract_no', sa.String(length=64), nullable=True),
    sa.Column('contract_base_price', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.Column('daily_volume_plan_nm3', sa.Numeric(precision=14, scale=3), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('notes', sa.String(length=512), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_gas_sources_code'), 'gas_sources', ['code'], unique=True)
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('full_name', sa.String(length=64), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.create_table('metering_stations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=16), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('location', sa.String(length=255), nullable=True),
    sa.Column('source_id', sa.Integer(), nullable=True),
    sa.Column('design_pressure_kpa', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('design_flow_min_nm3h', sa.Numeric(precision=12, scale=3), nullable=False),
    sa.Column('design_flow_max_nm3h', sa.Numeric(precision=12, scale=3), nullable=False),
    sa.Column('verified_until', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['source_id'], ['gas_sources.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_metering_stations_code'), 'metering_stations', ['code'], unique=True)
    op.create_table('settlement_records',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('settlement_no', sa.String(length=32), nullable=False),
    sa.Column('source_id', sa.Integer(), nullable=False),
    sa.Column('period_start', sa.Date(), nullable=False),
    sa.Column('period_end', sa.Date(), nullable=False),
    sa.Column('plant_volume_nm3', sa.Numeric(precision=16, scale=3), nullable=False),
    sa.Column('upstream_volume_nm3', sa.Numeric(precision=16, scale=3), nullable=True),
    sa.Column('diff_pct', sa.Numeric(precision=6, scale=3), nullable=True),
    sa.Column('avg_hhv_mj_nm3', sa.Numeric(precision=8, scale=3), nullable=True),
    sa.Column('total_energy_gj', sa.Numeric(precision=16, scale=3), nullable=True),
    sa.Column('contract_price', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.Column('amount', sa.Numeric(precision=16, scale=2), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('approver_id', sa.Integer(), nullable=True),
    sa.Column('approved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['approver_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['source_id'], ['gas_sources.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_settlement_records_settlement_no'), 'settlement_records', ['settlement_no'], unique=True)
    op.create_table('gc_analyzers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=16), nullable=False),
    sa.Column('model', sa.String(length=64), nullable=False),
    sa.Column('serial_no', sa.String(length=64), nullable=True),
    sa.Column('station_id', sa.Integer(), nullable=True),
    sa.Column('last_calibration_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('next_calibration_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['station_id'], ['metering_stations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_gc_analyzers_code'), 'gc_analyzers', ['code'], unique=True)
    op.create_table('metering_readings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('station_id', sa.Integer(), nullable=False),
    sa.Column('ts', sa.DateTime(timezone=True), nullable=False),
    sa.Column('actual_volume_rate_m3h', sa.Numeric(precision=12, scale=3), nullable=False),
    sa.Column('normal_volume_rate_nm3h', sa.Numeric(precision=12, scale=3), nullable=False),
    sa.Column('pressure_kpa', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('temperature_c', sa.Numeric(precision=6, scale=1), nullable=False),
    sa.Column('accumulated_volume_nm3', sa.Numeric(precision=16, scale=3), nullable=False),
    sa.Column('validity', sa.String(length=16), nullable=False),
    sa.Column('source', sa.String(length=8), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['station_id'], ['metering_stations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_metering_readings_station_id'), 'metering_readings', ['station_id'], unique=False)
    op.create_index('ix_metering_readings_station_ts', 'metering_readings', ['station_id', 'ts'], unique=False)
    op.create_index(op.f('ix_metering_readings_ts'), 'metering_readings', ['ts'], unique=False)
    op.create_table('alerts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('alert_no', sa.String(length=32), nullable=False),
    sa.Column('level', sa.String(length=16), nullable=False),
    sa.Column('category', sa.String(length=32), nullable=False),
    sa.Column('station_id', sa.Integer(), nullable=True),
    sa.Column('gc_id', sa.Integer(), nullable=True),
    sa.Column('source_id', sa.Integer(), nullable=True),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('payload_json', sa.JSON(), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('opened_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('acked_by', sa.Integer(), nullable=True),
    sa.Column('acked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('resolved_by', sa.Integer(), nullable=True),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['acked_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['gc_id'], ['gc_analyzers.id'], ),
    sa.ForeignKeyConstraint(['resolved_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['source_id'], ['gas_sources.id'], ),
    sa.ForeignKeyConstraint(['station_id'], ['metering_stations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_alerts_alert_no'), 'alerts', ['alert_no'], unique=True)
    op.create_index(op.f('ix_alerts_category'), 'alerts', ['category'], unique=False)
    op.create_table('gc_readings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('gc_id', sa.Integer(), nullable=False),
    sa.Column('station_id', sa.Integer(), nullable=True),
    sa.Column('ts', sa.DateTime(timezone=True), nullable=False),
    sa.Column('ch4_pct', sa.Numeric(precision=7, scale=4), nullable=False),
    sa.Column('c2h6_pct', sa.Numeric(precision=7, scale=4), nullable=False),
    sa.Column('c3h8_pct', sa.Numeric(precision=7, scale=4), nullable=False),
    sa.Column('ic4h10_pct', sa.Numeric(precision=7, scale=4), nullable=False),
    sa.Column('nc4h10_pct', sa.Numeric(precision=7, scale=4), nullable=False),
    sa.Column('n2_pct', sa.Numeric(precision=7, scale=4), nullable=False),
    sa.Column('co2_pct', sa.Numeric(precision=7, scale=4), nullable=False),
    sa.Column('others_pct', sa.Numeric(precision=7, scale=4), nullable=False),
    sa.Column('hhv_mj_nm3', sa.Numeric(precision=8, scale=3), nullable=False),
    sa.Column('lhv_mj_nm3', sa.Numeric(precision=8, scale=3), nullable=False),
    sa.Column('wobbe_mj_nm3', sa.Numeric(precision=8, scale=3), nullable=False),
    sa.Column('density_kg_nm3', sa.Numeric(precision=8, scale=4), nullable=False),
    sa.Column('validity', sa.String(length=16), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['gc_id'], ['gc_analyzers.id'], ),
    sa.ForeignKeyConstraint(['station_id'], ['metering_stations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_gc_readings_gc_id'), 'gc_readings', ['gc_id'], unique=False)
    op.create_index('ix_gc_readings_gc_ts', 'gc_readings', ['gc_id', 'ts'], unique=False)
    op.create_index(op.f('ix_gc_readings_ts'), 'gc_readings', ['ts'], unique=False)
    # ### end Alembic commands ###

def downgrade():
    raise RuntimeError("Destructive downgrade disabled; restore a verified backup instead")
