"""Frozen schema captured at 58a3fea; never import live ORM."""
from alembic import op
import sqlalchemy as sa

revision = '0002_archive'
down_revision = '0001_baseline'
branch_labels = None
depends_on = None

def upgrade():
# ### commands auto generated by Alembic - please adjust! ###
    op.create_table('reconciliation_runs',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('parent_run_id', sa.String(length=36), nullable=True),
    sa.Column('source_id', sa.Integer(), nullable=False),
    sa.Column('business_date', sa.Date(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_by', sa.String(length=128), nullable=False),
    sa.Column('snapshot_json', sa.JSON(), nullable=False),
    sa.Column('snapshot_sha256', sa.String(length=64), nullable=False),
    sa.ForeignKeyConstraint(['parent_run_id'], ['reconciliation_runs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_reconciliation_runs_business_date'), 'reconciliation_runs', ['business_date'], unique=False)
    op.create_index(op.f('ix_reconciliation_runs_parent_run_id'), 'reconciliation_runs', ['parent_run_id'], unique=False)
    op.create_index(op.f('ix_reconciliation_runs_source_id'), 'reconciliation_runs', ['source_id'], unique=False)
    # ### end Alembic commands ###

def downgrade():
    raise RuntimeError("Destructive downgrade disabled; restore a verified backup instead")
